<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>joepro-ide</AssemblyName>
    <RootNamespace>JoePro.Ide</RootNamespace>
    <ApplicationManifest Condition="Exists('app.manifest')">app.manifest</ApplicationManifest>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.3" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JoePro.Ui.Runtime\JoePro.Ui.Runtime.csproj" />
    <ProjectReference Include="..\JoePro.Migration\JoePro.Migration.csproj" />
    <ProjectReference Include="..\JoePro.Reports\JoePro.Reports.csproj" />
    <ProjectReference Include="..\JoePro.Tooling\JoePro.Tooling.csproj" />
  </ItemGroup>

</Project>
