<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JoePro.Core\JoePro.Core.csproj" />
    <ProjectReference Include="..\JoePro.Legacy.Formats\JoePro.Legacy.Formats.csproj" />
    <ProjectReference Include="..\JoePro.Data\JoePro.Data.csproj" />
    <ProjectReference Include="..\JoePro.Runtime\JoePro.Runtime.csproj" />
    <ProjectReference Include="..\JoePro.Language\JoePro.Language.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
