namespace JoePro.Tooling;

public static partial class FunctionDocs
{
    /// <summary>The rest of the built-in functions (the language reference covers every function the runtime implements).</summary>
    private static Dictionary<string, Doc> MoreFunctions() => new(StringComparer.OrdinalIgnoreCase)
    {
        // ---- Arrays ----
        ["ACLASS"] = new("ACLASS(ArrayName, oExpression)", "N", "Fills an array with an object's class and its parent classes."),
        ["ACOPY"] = new("ACOPY(SourceArray, DestinationArray [, nFirstSourceElement [, nNumberElements [, nFirstDestElement]]])", "N", "Copies elements from one array to another."),
        ["ASUBSCRIPT"] = new("ASUBSCRIPT(ArrayName, nElementNumber, nSubscript)", "N", "Row (1) or column (2) subscript of an element number."),
        ["AUSED"] = new("AUSED(ArrayName [, nDataSessionNumber])", "N", "Fills an array with the aliases and work areas in use."),
        ["ADATABASES"] = new("ADATABASES(ArrayName)", "N", "Fills an array with the open databases' names and paths."),
        ["ASESSIONS"] = new("ASESSIONS(ArrayName)", "N", "Fills an array with the data session numbers in use."),
        ["ASTACKINFO"] = new("ASTACKINFO(ArrayName)", "N", "Fills an array with the call stack: level, file, module, source file, line and source text."),
        ["APROCINFO"] = new("APROCINFO(ArrayName, cFileName [, nType])", "N", "Lists a program's procedures, classes, methods and #DEFINEs (nType 0 all, 1 procedures, 2 classes, 3 methods, 4 #DEFINEs)."),
        ["ATAGINFO"] = new("ATAGINFO(ArrayName [, cCDXName [, nWorkArea | cTableAlias]])", "N", "Fills an array with each index tag's name, type, key, filter, order and collation."),
        ["AERROR"] = new("AERROR(ArrayName)", "N", "Fills an array with information about the last error."),
        ["ALANGUAGE"] = new("ALANGUAGE(ArrayName, nType)", "N", "Fills an array with the language's commands (1), functions (2), base classes (3) or DBC events (4)."),
        ["AFONT"] = new("AFONT(ArrayName [, cFontName [, nFontSize]])", "L", "Fills an array with the available font names, or checks a font and size."),
        ["AGETCLASS"] = new("AGETCLASS(ArrayName [, cLibraryName [, cClassName [, cTitleText …]]])", "L", "Shows the Open class dialog; the array receives the library and class chosen."),
        ["AGETFILEVERSION"] = new("AGETFILEVERSION(ArrayName, cFileName)", "N", "Fills an array with a file's version resource (company, description, versions…)."),
        ["ANETRESOURCES"] = new("ANETRESOURCES(ArrayName, cNetworkName, nResourceType)", "N", "Network shares or printers of a server (0 where the platform has none)."),
        ["APRINTERS"] = new("APRINTERS(ArrayName [, nValue])", "N", "Fills an array with the installed printers."),
        ["ASELOBJ"] = new("ASELOBJ(ArrayName [, 1 | 2])", "N", "Objects selected in a designer (none when a program runs outside a designer)."),
        ["AVCXCLASSES"] = new("AVCXCLASSES(ArrayName, cLibraryName)", "N", "Fills an array with the classes in a class library."),

        // ---- Characters ----
        ["AT_C"] = new("AT_C(cSearchExpression, cExpressionSearched [, nOccurrence])", "N", "Like AT(); strings are Unicode, so the same as AT()."),
        ["ATCC"] = new("ATCC(cSearchExpression, cExpressionSearched [, nOccurrence])", "N", "Like ATC(); strings are Unicode, so the same as ATC()."),
        ["RATC"] = new("RATC(cSearchExpression, cExpressionSearched [, nOccurrence])", "N", "Like RAT(); strings are Unicode, so the same as RAT()."),
        ["ATLINE"] = new("ATLINE(cSearchExpression, cExpressionSearched)", "N", "Line number of the first line containing the text (0 if none)."),
        ["ATCLINE"] = new("ATCLINE(cSearchExpression, cExpressionSearched)", "N", "Like ATLINE(), case-insensitive."),
        ["RATLINE"] = new("RATLINE(cSearchExpression, cExpressionSearched)", "N", "Line number of the last line containing the text (0 if none)."),
        ["LEFTC"] = new("LEFTC(cExpression, nExpression)", "C", "Leftmost characters (same as LEFT())."),
        ["RIGHTC"] = new("RIGHTC(cExpression, nCharacters)", "C", "Rightmost characters (same as RIGHT())."),
        ["SUBSTRC"] = new("SUBSTRC(cExpression, nStartPosition [, nCharactersReturned])", "C", "Part of a string (same as SUBSTR())."),
        ["LENC"] = new("LENC(cExpression)", "N", "Number of characters (same as LEN())."),
        ["LIKEC"] = new("LIKEC(cExpression1, cExpression2)", "L", "Wildcard match (same as LIKE())."),
        ["STUFFC"] = new("STUFFC(cExpression, nStartReplacement, nCharactersReplaced, cReplacement)", "C", "Replaces characters in a string (same as STUFF())."),
        ["CHRTRANC"] = new("CHRTRANC(cSearched, cSearchFor, cReplacement)", "C", "Translates characters one-for-one (same as CHRTRAN())."),
        ["ISALPHA"] = new("ISALPHA(cExpression)", "L", "True if the first character is a letter."),
        ["ISDIGIT"] = new("ISDIGIT(cExpression)", "L", "True if the first character is a digit."),
        ["ISLOWER"] = new("ISLOWER(cExpression)", "L", "True if the first character is a lowercase letter."),
        ["ISUPPER"] = new("ISUPPER(cExpression)", "L", "True if the first character is an uppercase letter."),
        ["ISLEADBYTE"] = new("ISLEADBYTE(cExpression)", "L", "Always false: strings are Unicode, there are no lead bytes."),
        ["ISBLANK"] = new("ISBLANK(eExpression)", "L", "True if a value (or field) is blank."),
        ["MEMLINES"] = new("MEMLINES(MemoFieldName)", "N", "Number of lines in a memo or string."),
        ["MLINE"] = new("MLINE(MemoFieldName, nLineNumber [, nNumberOfCharacters])", "C", "One line of a memo or string."),
        ["SOUNDEX"] = new("SOUNDEX(cExpression)", "C", "Four-character phonetic code."),
        ["DIFFERENCE"] = new("DIFFERENCE(cExpression1, cExpression2)", "N", "Phonetic similarity from 0 (different) to 4 (alike)."),
        ["STRCONV"] = new("STRCONV(cExpression, nConversionSetting [, nRegionalIdentifier [, nRegionalIDType]])", "C", "Converts between encodings: UTF-8 (9/11), Unicode (5/6), Base64 (13/14), hex (15/16)."),
        ["CPCONVERT"] = new("CPCONVERT(nCurrentCodePage, nNewCodePage, cExpression)", "C", "Code page conversion; strings are Unicode once read, so the text is returned as is."),
        ["CPCURRENT"] = new("CPCURRENT([1 | 2])", "N", "The current code page (1252)."),
        ["CPDBF"] = new("CPDBF([nWorkArea | cTableAlias])", "N", "The code page of a table (0: tables store Unicode)."),
        ["OEMTOANSI"] = new("OEMTOANSI(cExpression)", "C", "OEM to ANSI conversion; strings are Unicode, so the text is returned as is."),
        ["CREATEBINARY"] = new("CREATEBINARY(cExpression)", "Q", "Converts a string to a binary (varbinary) value."),
        ["NORMALIZE"] = new("NORMALIZE(cExpression)", "C", "An expression in canonical form: names upper-cased, -> turned into '.'."),
        ["PROPER"] = new("PROPER(cExpression)", "C", "Capitalizes the first letter of each word."),
        ["DISPLAYPATH"] = new("DISPLAYPATH(cFileName, nMaxLength)", "C", "A path shortened with \"...\" to fit a length."),

        // ---- Binary and numbers ----
        ["BINTOC"] = new("BINTOC(nExpression [, nSize | cFlags])", "C", "Converts an integer to a binary character representation (sortable)."),
        ["CTOBIN"] = new("CTOBIN(cExpression [, cFlags])", "N", "Converts a binary character representation back to a number."),
        ["BITCLEAR"] = new("BITCLEAR(nExpression1, nExpression2)", "N", "Clears a bit."),
        ["BITLSHIFT"] = new("BITLSHIFT(nExpression1, nExpression2)", "N", "Shifts bits left."),
        ["BITNOT"] = new("BITNOT(nExpression)", "N", "Bitwise NOT."),
        ["BITOR"] = new("BITOR(nExpression1, nExpression2 [, …])", "N", "Bitwise OR."),
        ["BITRSHIFT"] = new("BITRSHIFT(nExpression1, nExpression2)", "N", "Shifts bits right."),
        ["BITSET"] = new("BITSET(nExpression1, nExpression2)", "N", "Sets a bit."),
        ["BITTEST"] = new("BITTEST(nExpression1, nExpression2)", "L", "True if a bit is set."),
        ["BITXOR"] = new("BITXOR(nExpression1, nExpression2 [, …])", "N", "Bitwise exclusive OR."),
        ["ACOS"] = new("ACOS(nExpression)", "N", "Arc cosine in radians."),
        ["ASIN"] = new("ASIN(nExpression)", "N", "Arc sine in radians."),
        ["ATAN"] = new("ATAN(nExpression)", "N", "Arc tangent in radians."),
        ["ATN2"] = new("ATN2(nYCoordinate, nXCoordinate)", "N", "Arc tangent of y/x in radians, in the right quadrant."),
        ["COS"] = new("COS(nExpression)", "N", "Cosine of an angle in radians."),
        ["SIN"] = new("SIN(nExpression)", "N", "Sine of an angle in radians."),
        ["TAN"] = new("TAN(nExpression)", "N", "Tangent of an angle in radians."),
        ["DTOR"] = new("DTOR(nExpression)", "N", "Degrees to radians."),
        ["RTOD"] = new("RTOD(nExpression)", "N", "Radians to degrees."),
        ["PI"] = new("PI()", "N", "The constant π."),
        ["EXP"] = new("EXP(nExpression)", "N", "e raised to a power."),
        ["LOG"] = new("LOG(nExpression)", "N", "Natural logarithm."),
        ["LOG10"] = new("LOG10(nExpression)", "N", "Base-10 logarithm."),
        ["SIGN"] = new("SIGN(nExpression)", "N", "1, -1 or 0 by the sign of the value."),
        ["RAND"] = new("RAND([nSeedValue])", "N", "Random number between 0 and 1 (a negative seed seeds from the clock)."),
        ["FV"] = new("FV(nPayment, nInterestRate, nPeriods)", "N", "Future value of an investment."),
        ["PV"] = new("PV(nPayment, nInterestRate, nTotalPayments)", "N", "Present value of an investment."),
        ["PAYMENT"] = new("PAYMENT(nPrincipal, nInterestRate, nPayments)", "N", "Amount of each payment on a loan."),
        ["MTON"] = new("MTON(mExpression)", "N", "Currency to numeric."),
        ["NTOM"] = new("NTOM(nExpression)", "Y", "Numeric to currency."),
        ["RGB"] = new("RGB(nRedValue, nGreenValue, nBlueValue)", "N", "A color value from red, green and blue (0–255)."),

        // ---- Dates and times ----
        ["DMY"] = new("DMY(dExpression | tExpression)", "C", "Date as day month year text."),
        ["MDY"] = new("MDY(dExpression | tExpression)", "C", "Date as month day, year text."),
        ["DTOT"] = new("DTOT(dDateExpression)", "T", "Date to datetime at midnight."),
        ["HOUR"] = new("HOUR(tExpression)", "N", "Hour of a datetime."),
        ["MINUTE"] = new("MINUTE(tExpression)", "N", "Minute of a datetime."),
        ["SEC"] = new("SEC(tExpression)", "N", "Seconds of a datetime."),
        ["SECONDS"] = new("SECONDS()", "N", "Seconds since midnight, with milliseconds."),
        ["QUARTER"] = new("QUARTER(dExpression | tExpression [, nMonth])", "N", "Quarter of the year (optionally of a fiscal year starting in nMonth)."),
        ["WEEK"] = new("WEEK(dExpression | tExpression [, nFirstWeek] [, nFirstDayOfWeek])", "N", "Week of the year."),

        // ---- Tables, indexes and buffering ----
        ["CANDIDATE"] = new("CANDIDATE([nIndexNumber] [, nWorkArea | cTableAlias])", "L", "True if an index tag is a candidate (or primary) key."),
        ["PRIMARY"] = new("PRIMARY([nIndexNumber] [, nWorkArea | cTableAlias])", "L", "True if an index tag is the primary key."),
        ["UNIQUE"] = new("UNIQUE([cIndexFile,] [nIndexNumber] [, nWorkArea | cTableAlias])", "L", "True if an index tag was created UNIQUE."),
        ["DESCENDING"] = new("DESCENDING([cIndexFile,] [nIndexNumber] [, nWorkArea | cTableAlias])", "L", "True if an index tag is descending."),
        ["TAG"] = new("TAG([cIndexFile,] nTagNumber [, nWorkArea | cTableAlias])", "C", "Name of an index tag."),
        ["TAGCOUNT"] = new("TAGCOUNT([cIndexFile [, nWorkArea | cTableAlias]])", "N", "Number of index tags."),
        ["TAGNO"] = new("TAGNO([cIndexName [, cIndexFile [, nWorkArea | cTableAlias]]])", "N", "Position of an index tag."),
        ["KEY"] = new("KEY([cIndexFile,] [nIndexNumber] [, nWorkArea | cTableAlias])", "C", "Key expression of an index tag."),
        ["FOR"] = new("FOR([nIndexNumber [, nWorkArea | cTableAlias]])", "C", "Filter expression of an index tag."),
        ["IDXCOLLATE"] = new("IDXCOLLATE([cIndexFile,] nIndexNumber [, nWorkArea | cTableAlias])", "C", "Collation sequence of an index tag."),
        ["CDX"] = new("CDX(nIndexNumber [, nWorkArea | cTableAlias])", "C", "The structural index name (every table's tags live in it)."),
        ["KEYMATCH"] = new("KEYMATCH(eIndexKey [, nIndexNumber [, nWorkArea | cTableAlias]])", "L", "True if a key exists in an index, without moving the record pointer."),
        ["INDEXSEEK"] = new("INDEXSEEK(eExpression [, lMovePointer [, nWorkArea | cTableAlias [, nIndexNumber | cIndexTag]]])", "L", "Seeks a key, optionally leaving the record pointer where it was."),
        ["LOOKUP"] = new("LOOKUP(ReturnField, eSearchExpression, SearchedField [, cTagName])", "V", "Finds a record by key and returns a field from it."),
        ["FILTER"] = new("FILTER([nWorkArea | cTableAlias])", "C", "The SET FILTER expression of a work area."),
        ["RELATION"] = new("RELATION(nRelationNumber [, nWorkArea | cTableAlias])", "C", "Expression of a SET RELATION."),
        ["TARGET"] = new("TARGET(nRelationNumber [, nWorkArea | cTableAlias])", "C", "Alias a SET RELATION points into."),
        ["FSIZE"] = new("FSIZE(cFieldName [, nWorkArea | cTableAlias])", "N", "Width of a field."),
        ["RECSIZE"] = new("RECSIZE([nWorkArea | cTableAlias])", "N", "Record width (the sum of the field widths plus the deletion flag)."),
        ["HEADER"] = new("HEADER([nWorkArea | cTableAlias])", "N", "Size a VFP table header of this structure would have."),
        ["LUPDATE"] = new("LUPDATE([nWorkArea | cTableAlias])", "D", "Date the table was last changed."),
        ["DBC"] = new("DBC()", "C", "Path of the current database."),
        ["DBUSED"] = new("DBUSED(cDatabaseName)", "L", "True if a database is open."),
        ["DBGETPROP"] = new("DBGETPROP(cName, cType, cProperty)", "V", "Reads a property of the database, a table, field, view or connection."),
        ["ISEXCLUSIVE"] = new("ISEXCLUSIVE([cTableAlias | nWorkArea | cDatabaseName [, nType]])", "L", "True if a table (or database) is open exclusively."),
        ["ISREADONLY"] = new("ISREADONLY([nWorkArea | cTableAlias])", "L", "True if a table is open read-only."),
        ["ISFLOCKED"] = new("ISFLOCKED([nWorkArea | cTableAlias])", "L", "True if the table is locked."),
        ["ISRLOCKED"] = new("ISRLOCKED([nRecordNumber, [nWorkArea | cTableAlias]])", "L", "True if a record is locked."),
        ["FLOCK"] = new("FLOCK([nWorkArea | cTableAlias])", "L", "Locks a table; true on success."),
        ["LOCK"] = new("LOCK([nWorkArea | cTableAlias] | [cRecordNumberList, nWorkArea | cTableAlias])", "L", "Locks records (same as RLOCK())."),
        ["ISTRANSACTABLE"] = new("ISTRANSACTABLE([nWorkArea | cTableAlias])", "L", "True if a table takes part in transactions (all Joe Pro tables do)."),
        ["MAKETRANSACTABLE"] = new("MAKETRANSACTABLE([nWorkArea | cTableAlias])", "L", "Makes a free table transactable (all Joe Pro tables already are)."),
        ["ISMEMOFETCHED"] = new("ISMEMOFETCHED(cFieldName | nFieldNumber [, nWorkArea | cTableAlias])", "L", "True if a memo has been fetched (memos are always fetched)."),
        ["TXNLEVEL"] = new("TXNLEVEL()", "N", "Current transaction nesting level."),
        ["GETNEXTMODIFIED"] = new("GETNEXTMODIFIED(nRecordNumber [, cTableAlias | nWorkArea] [, lNoFire])", "N", "Next record with buffered changes after nRecordNumber (0 if none)."),
        ["SETFLDSTATE"] = new("SETFLDSTATE(cFieldName | nFieldNumber, nFieldState [, cTableAlias | nWorkArea])", "L", "Marks a buffered field unchanged (1, 3) or changed (2, 4)."),
        ["GETAUTOINCVALUE"] = new("GETAUTOINCVALUE([nDataSessionNumber])", "N", "The last autoincrement value generated."),
        ["GETCURSORADAPTER"] = new("GETCURSORADAPTER([cAlias])", "O", "The CursorAdapter object that owns a cursor."),
        ["SETRESULTSET"] = new("SETRESULTSET(nWorkArea | cTableAlias)", "N", "Marks a cursor as the result set."),
        ["GETRESULTSET"] = new("GETRESULTSET()", "N", "Work area of the cursor marked as the result set."),
        ["CLEARRESULTSET"] = new("CLEARRESULTSET()", "N", "Clears the result-set mark; returns the work area it was on."),
        ["CURSORTOXML"] = new("CURSORTOXML(nWorkArea | cTableAlias, cOutput [, nOutputFormat [, nFlags [, nRecords [, cSchemaName …]]]])", "N", "Writes a cursor as XML into a variable or file (512); \"1\" as the schema name adds an inline XSD."),
        ["XMLTOCURSOR"] = new("XMLTOCURSOR(eExpression | cXMLFile [, cCursorName [, nFlags]])", "N", "Creates a cursor from XML; types come from an inline schema or from the data."),
        ["SQLCANCEL"] = new("SQLCANCEL(nStatementHandle)", "N", "Cancels a running pass-through statement."),
        ["SQLIDLEDISCONNECT"] = new("SQLIDLEDISCONNECT(nStatementHandle)", "N", "Releases an idle connection (it reconnects when used)."),

        // ---- Low-level files and the file system ----
        ["FCREATE"] = new("FCREATE(cFileName [, nFileAttribute])", "N", "Creates a file; returns a file handle or -1."),
        ["FOPEN"] = new("FOPEN(cFileName [, nAttribute])", "N", "Opens a file (0 read, 1 write, 2 read/write); returns a handle or -1."),
        ["FCLOSE"] = new("FCLOSE(nFileHandle)", "L", "Closes a file handle."),
        ["FREAD"] = new("FREAD(nFileHandle, nBytes)", "C", "Reads bytes from a file."),
        ["FGETS"] = new("FGETS(nFileHandle [, nBytes])", "C", "Reads a line from a file."),
        ["FWRITE"] = new("FWRITE(nFileHandle, cExpression [, nCharactersWritten])", "N", "Writes to a file; returns the bytes written."),
        ["FPUTS"] = new("FPUTS(nFileHandle, cExpression [, nCharactersWritten])", "N", "Writes a line and a carriage return/line feed."),
        ["FSEEK"] = new("FSEEK(nFileHandle, nBytesMoved [, nRelativePosition])", "N", "Moves the file pointer (0 start, 1 end, 2 current)."),
        ["FEOF"] = new("FEOF(nFileHandle)", "L", "True at the end of the file."),
        ["FFLUSH"] = new("FFLUSH(nFileHandle [, lForce])", "L", "Flushes a file to disk."),
        ["FCHSIZE"] = new("FCHSIZE(nFileHandle, nNewFileSize)", "N", "Changes a file's size."),
        ["FERROR"] = new("FERROR()", "N", "Operating-system error of the last low-level file function (0 if none)."),
        ["FDATE"] = new("FDATE(cFileName [, nType])", "D", "Date a file was last modified (nType 1: datetime)."),
        ["FTIME"] = new("FTIME(cFileName)", "C", "Time a file was last modified (hh:mm:ss)."),
        ["FULLPATH"] = new("FULLPATH(cFileName1 [, nMSDOSPath | cFileName2])", "C", "Full path of a file."),
        ["CURDIR"] = new("CURDIR([cExpression])", "C", "The current directory."),
        ["DIRECTORY"] = new("DIRECTORY(cDirectoryName [, nFlags])", "L", "True if a directory exists."),
        ["DEFAULTEXT"] = new("DEFAULTEXT(cFileName, cDefault)", "C", "Adds an extension if the name has none."),
        ["FORCEEXT"] = new("FORCEEXT(cFileName, cExtension)", "C", "Replaces a file name's extension."),
        ["FORCEPATH"] = new("FORCEPATH(cFileName, cPath)", "C", "Replaces a file name's path."),
        ["JUSTDRIVE"] = new("JUSTDRIVE(cPath)", "C", "Drive letter of a path."),
        ["JUSTEXT"] = new("JUSTEXT(cPath)", "C", "Extension of a file name."),
        ["JUSTFNAME"] = new("JUSTFNAME(cFileName)", "C", "File name without the path."),
        ["JUSTPATH"] = new("JUSTPATH(cFileName)", "C", "Path without the file name."),
        ["JUSTSTEM"] = new("JUSTSTEM(cFileName)", "C", "File name without path or extension."),
        ["DISKSPACE"] = new("DISKSPACE([cVolumeName [, nType]])", "N", "Free space on a drive (nType 1 total, 2 free, 3 free to the user)."),
        ["DRIVETYPE"] = new("DRIVETYPE(cDrive)", "N", "Type of a drive (1 none, 2 removable, 3 fixed, 4 network, 5 CD)."),
        ["LOCFILE"] = new("LOCFILE(cFileName [, cFileExtensions] [, cFileNameCaption])", "C", "Finds a file on the default folder and SET PATH, else asks the user."),
        ["GETFILE"] = new("GETFILE([cFileExtensions] [, cText] [, cOpenButtonCaption] [, nButtonType] [, cTitleBarCaption])", "C", "Open File dialog; the chosen path or an empty string."),
        ["PUTFILE"] = new("PUTFILE([cCustomText] [, cFileName] [, cFileExtensions])", "C", "Save As dialog; the chosen path or an empty string."),
        ["GETPICT"] = new("GETPICT([cFileExtensions] [, cFileNameCaption] [, cOpenButtonCaption])", "C", "Open Picture dialog."),
        ["GETDIR"] = new("GETDIR([cDirectory [, cText [, cCaption [, nFlags [, lRootOnly]]]]])", "C", "Select Directory dialog."),

        // ---- Environment ----
        ["GETENV"] = new("GETENV(cVariableName)", "C", "Value of an environment variable."),
        ["HOME"] = new("HOME([nLocation])", "C", "The Joe Pro program folder (or samples 2, graphics 4, SDK 5, shared data 6, user data 7)."),
        ["OS"] = new("OS([1])", "C", "Name (or version) of the operating system."),
        ["MEMORY"] = new("MEMORY()", "N", "Available memory in kilobytes."),
        ["SYSMETRIC"] = new("SYSMETRIC(nScreenElement)", "N", "Size of a screen element (1 screen width, 2 height, 9 caption height…)."),
        ["SCOLS"] = new("SCOLS()", "N", "Columns of the main window in character units."),
        ["SROWS"] = new("SROWS()", "N", "Rows of the main window in character units."),
        ["FONTMETRIC"] = new("FONTMETRIC(nAttribute [, cFontName, nFontSize [, cFontStyle]])", "N", "A font measurement (1 height, 2 ascent, 3 descent, 6 average width…)."),
        ["TXTWIDTH"] = new("TXTWIDTH(cExpression [, cFontName, nFontSize [, cFontStyle]])", "N", "Length of text in average character widths of a font."),
        ["GETFONT"] = new("GETFONT([cFontName [, nFontSize [, cFontStyle [, nFontCharSet]]]])", "C", "Font dialog; returns \"name,size,style\" or an empty string."),
        ["GETCOLOR"] = new("GETCOLOR([nDefaultColorNumber])", "N", "Color dialog; the chosen color or -1."),
        ["GETCP"] = new("GETCP([nCodePage] [, cText] [, cDialogTitle])", "N", "Code page dialog; returns the default code page without a user interface."),
        ["GETPRINTER"] = new("GETPRINTER()", "C", "Printer dialog; the chosen printer or an empty string."),
        ["PRINTSTATUS"] = new("PRINTSTATUS()", "L", "True if the printer is ready."),
        ["PRTINFO"] = new("PRTINFO(nPrinterSetting [, cPrinterName])", "N", "A printer setting (orientation, paper size, copies…)."),
        ["ISCOLOR"] = new("ISCOLOR()", "L", "True on a color display."),
        ["ISMOUSE"] = new("ISMOUSE()", "L", "True if a mouse is present."),
        ["ISHOSTED"] = new("ISHOSTED()", "L", "True when running in a browser host (never)."),
        ["CAPSLOCK"] = new("CAPSLOCK([lExpression])", "L", "State of Caps Lock."),
        ["NUMLOCK"] = new("NUMLOCK([lExpression])", "L", "State of Num Lock."),
        ["INSMODE"] = new("INSMODE([lExpression])", "L", "Insert mode."),
        ["INKEY"] = new("INKEY([nSeconds] [, cHideCursor])", "N", "Next key in the keyboard buffer (filled by KEYBOARD), or 0."),
        ["LASTKEY"] = new("LASTKEY()", "N", "Code of the last key read."),
        ["CHRSAW"] = new("CHRSAW([nSeconds])", "L", "True if a key is waiting in the keyboard buffer."),
        ["FKLABEL"] = new("FKLABEL(nFunctionKeyNumber)", "C", "Name of a function key (F1…F12)."),
        ["FKMAX"] = new("FKMAX()", "N", "Number of programmable function keys (12)."),
        ["INPUTBOX"] = new("INPUTBOX(cInputPrompt [, cDialogCaption] [, cDefaultValue] [, nTimeout [, cTimeoutValue [, cCancelValue]]])", "C", "Asks the user for a line of text."),
        ["ROW"] = new("ROW()", "N", "Current row of the character-mode cursor (0)."),
        ["COL"] = new("COL()", "N", "Current column of the character-mode cursor (0)."),
        ["PROW"] = new("PROW()", "N", "Current printer row (0)."),
        ["PCOL"] = new("PCOL()", "N", "Current printer column (0)."),
        ["WEXIST"] = new("WEXIST(WindowName)", "L", "True if a user-defined window exists (DEFINE WINDOW is not supported, so always false)."),
        ["WONTOP"] = new("WONTOP([WindowName])", "C", "Name of the frontmost user-defined window."),
        ["WOUTPUT"] = new("WOUTPUT([WindowName])", "C", "Name of the window output goes to."),
        ["WTITLE"] = new("WTITLE([WindowName])", "C", "Title of a user-defined window."),
        ["WVISIBLE"] = new("WVISIBLE(WindowName)", "L", "True if a user-defined window is visible."),

        // ---- Program state and errors ----
        ["ERROR"] = new("ERROR()", "N", "Number of the last error."),
        ["MESSAGE"] = new("MESSAGE([1])", "C", "Message of the last error."),
        ["LINENO"] = new("LINENO([1])", "N", "Line number being executed."),
        ["PARAMETERS"] = new("PARAMETERS()", "N", "Number of parameters passed to the most recent call (like PCOUNT())."),
        ["ON"] = new("ON(cOnCommand [, KeyLabelName])", "C", "The command set with ON ERROR, ON KEY LABEL, ON SHUTDOWN, ON ESCAPE…"),
        ["REFRESH"] = new("REFRESH([nRecords [, nRecordOffset]] [, cTableAlias | nWorkArea])", "N", "Re-reads buffered records from disk; returns the number refreshed."),
        ["NODEFAULT"] = new("NODEFAULT", "", "Prevents the base class behavior of the running event."),
        ["DODEFAULT"] = new("DODEFAULT([eParameter1, …])", "V", "Runs the parent class's version of the running method."),

        // ---- Objects and events ----
        ["COMPOBJ"] = new("COMPOBJ(oExpression1, oExpression2)", "L", "True if two objects have the same properties and values."),
        ["GETPEM"] = new("GETPEM(oObjectName | cClassName, cProperty | cEvent | cMethod)", "V", "Value of a property, or the code of a method."),
        ["REMOVEPROPERTY"] = new("REMOVEPROPERTY(oObjectName, cPropertyName)", "L", "Removes a property added at run time."),
        ["RAISEEVENT"] = new("RAISEEVENT(oEventSource, cEvent [, eParm1, …])", "V", "Raises an event (runs the method and anything bound with BINDEVENT)."),
        ["BINDEVENT"] = new("BINDEVENT(oEventSource, cEvent, oEventHandler, cDelegate [, nFlags])", "N", "Runs a delegate method whenever an event or method runs."),
        ["UNBINDEVENTS"] = new("UNBINDEVENTS(oEventObject [, cEvent, oEventHandler, cDelegate])", "N", "Removes event bindings."),
        ["OBJTOCLIENT"] = new("OBJTOCLIENT(oObjectName, nPosition)", "N", "Top (1), left (2), width (3) or height (4) of a control relative to its form."),
        ["GETOBJECT"] = new("GETOBJECT(cFileName [, cClassName])", "O", "Attaches to a COM object (Windows only)."),
        ["CREATEOBJECTEX"] = new("CREATEOBJECTEX(cCLSID | cPROGID, cComputerName [, cIID])", "O", "Creates a COM object on another computer (Windows only)."),

        // ---- Menus ----
        ["BAR"] = new("BAR()", "N", "Number of the menu bar chosen last."),
        ["CNTBAR"] = new("CNTBAR(cMenuName)", "N", "Number of bars in a popup."),
        ["CNTPAD"] = new("CNTPAD(cMenuBarName)", "N", "Number of pads in a menu bar."),
        ["GETBAR"] = new("GETBAR(MenuItemName, nMenuPosition)", "N", "Number of the bar at a position in a popup."),
        ["GETPAD"] = new("GETPAD(cMenuBarName, nMenuBarPosition)", "C", "Name of the pad at a position in a menu bar."),
        ["MENU"] = new("MENU()", "C", "Name of the active menu bar."),
        ["PAD"] = new("PAD([cMenuPadName [, cMenuBarName]])", "C", "Name of the pad chosen last."),
        ["POPUP"] = new("POPUP([cMenuName])", "C", "Name of the active popup."),
        ["PROMPT"] = new("PROMPT()", "C", "Prompt text of the menu item chosen last."),
        ["PRMBAR"] = new("PRMBAR(MenuName, nMenuItemNumber)", "C", "Prompt text of a bar."),
        ["PRMPAD"] = new("PRMPAD(MenuBarName, MenuTitleName)", "C", "Prompt text of a pad."),
        ["MRKBAR"] = new("MRKBAR(cMenuName, nMenuItemNumber | cSystemMenuItemName)", "L", "True if a bar is marked."),
        ["MRKPAD"] = new("MRKPAD(cMenuBarName, cMenuTitleName)", "L", "True if a pad is marked."),
        ["SKPBAR"] = new("SKPBAR(cMenuName, MenuItemNumber)", "L", "True if a bar is disabled (SKIP FOR)."),
        ["SKPPAD"] = new("SKPPAD(cMenuBarName, cMenuTitleName)", "L", "True if a pad is disabled (SKIP FOR)."),
    };

    private static IReadOnlyDictionary<string, Doc> Merge(Dictionary<string, Doc> core)
    {
        foreach (var (k, v) in MoreFunctions()) core.TryAdd(k, v);
        return core;
    }
}
