namespace JoePro.Tooling;

/// <summary>Signatures and one-line descriptions of built-in functions and commands (hover, completion, signature help).</summary>
public static partial class FunctionDocs
{
    public sealed record Doc(string Signature, string Returns, string Summary);

    public static readonly IReadOnlyDictionary<string, Doc> Functions = Merge(new Dictionary<string, Doc>(StringComparer.OrdinalIgnoreCase)
    {
        ["ABS"] = new("ABS(nExpression)", "N", "Absolute value."),
        ["SQLSTRINGCONNECT"] = new("SQLSTRINGCONNECT(cConnectString [, lSharable])", "N", "Opens a pass-through connection; returns a handle or -1. \"Provider=sqlite;…\" or an ODBC string (Driver=…, DSN=…)."),
        ["SQLCONNECT"] = new("SQLCONNECT(cDataSourceName, cUserID, cPassword [, lShared] | cConnectionName)", "N", "Connects to an ODBC data source or a named connection in the database."),
        ["SQLDISCONNECT"] = new("SQLDISCONNECT(nConnectionHandle)", "N", "Closes a connection (0 closes all)."),
        ["SQLEXEC"] = new("SQLEXEC(nConnectionHandle [, cSQLCommand [, cCursorName [, aCountInfo]]])", "N", "Runs native SQL; ?name and ?(expr) are parameters. Returns the number of result cursors, or -1."),
        ["SQLPREPARE"] = new("SQLPREPARE(nConnectionHandle, cSQLCommand [, cCursorName])", "N", "Prepares a statement for the next SQLEXEC(nConnectionHandle)."),
        ["SQLMORERESULTS"] = new("SQLMORERESULTS(nConnectionHandle)", "N", "Fetches the next result set when BatchMode is off (2 when there are no more)."),
        ["SQLCOMMIT"] = new("SQLCOMMIT(nConnectionHandle)", "N", "Commits a manual transaction."),
        ["SQLROLLBACK"] = new("SQLROLLBACK(nConnectionHandle)", "N", "Rolls back a manual transaction."),
        ["SQLTABLES"] = new("SQLTABLES(nConnectionHandle [, cTableTypes] [, cCursorName])", "N", "Creates a cursor listing the server's tables and views."),
        ["SQLCOLUMNS"] = new("SQLCOLUMNS(nConnectionHandle, cTableName [, \"FOXPRO\" | \"NATIVE\"] [, cCursorName])", "N", "Creates a cursor describing a table's columns."),
        ["SQLGETPROP"] = new("SQLGETPROP(nConnectionHandle, cSetting)", "", "Reads a connection setting (0 = defaults for new connections)."),
        ["SQLSETPROP"] = new("SQLSETPROP(nConnectionHandle, cSetting [, eExpression])", "N", "Changes a connection setting such as Transactions, BatchMode or QueryTimeOut."),
        ["ASQLHANDLES"] = new("ASQLHANDLES(ArrayName [, nStatementHandle])", "N", "Fills an array with the active connection handles."),
        ["DBSETPROP"] = new("DBSETPROP(cName, cType, cProperty, ePropertyValue)", "L", "Sets a property of a view, view field or connection in the current database."),
        ["ADBOBJECTS"] = new("ADBOBJECTS(ArrayName, cSetting)", "N", "Fills an array with the database's TABLE, VIEW, CONNECTION or RELATION names."),
        ["INDBC"] = new("INDBC(cDatabaseObjectName, cType)", "L", "True if the object exists in the current database."),
        ["REQUERY"] = new("REQUERY([nWorkArea | cTableAlias])", "N", "Runs a view's query again with the current parameter values."),
        ["AEVENTS"] = new("AEVENTS(ArrayName, 0 | oObject)", "N", "The event source running the current delegate (0), or an object's BINDEVENT bindings."),
        ["ADDBS"] = new("ADDBS(cPath)", "C", "Adds a trailing backslash to a path if needed."),
        ["ADDPROPERTY"] = new("ADDPROPERTY(oObject, cPropertyName [, eValue])", "L", "Adds a property to an object at run time."),
        ["ADEL"] = new("ADEL(ArrayName, nElementNumber [, 2])", "N", "Deletes an element, row or column from an array."),
        ["ADIR"] = new("ADIR(ArrayName [, cFileSkeleton [, cAttribute]])", "N", "Fills an array with file information; returns the number of files."),
        ["AELEMENT"] = new("AELEMENT(ArrayName, nRow [, nColumn])", "N", "Element number from row and column subscripts."),
        ["AFIELDS"] = new("AFIELDS(ArrayName [, nWorkArea | cTableAlias])", "N", "Fills an array with the structure of a table."),
        ["AINS"] = new("AINS(ArrayName, nElementNumber [, 2])", "N", "Inserts an element, row or column into an array."),
        ["ALEN"] = new("ALEN(ArrayName [, nArrayAttribute])", "N", "Number of elements (0), rows (1) or columns (2)."),
        ["ALIAS"] = new("ALIAS([nWorkArea | cTableAlias])", "C", "Alias of the current or specified work area."),
        ["ALINES"] = new("ALINES(ArrayName, cExpression [, nFlags] [, cParseChar …])", "N", "Splits text into lines (or on parse characters) into an array."),
        ["ALLTRIM"] = new("ALLTRIM(cExpression [, nFlags] [, cParseChar …])", "C", "Removes leading and trailing blanks (or the given characters)."),
        ["AMEMBERS"] = new("AMEMBERS(ArrayName, oObject [, nArrayContentsID])", "N", "Fills an array with an object's property (and method) names."),
        ["ASC"] = new("ASC(cExpression)", "N", "Character code of the first character."),
        ["ASCAN"] = new("ASCAN(ArrayName, eExpression [, nStart [, nCount [, nSearchColumn [, nFlags]]]])", "N", "Searches an array; returns the element (or row) number."),
        ["ASORT"] = new("ASORT(ArrayName [, nStart [, nCount [, nSortOrder [, nFlags]]]])", "N", "Sorts an array (descending when nSortOrder = 1)."),
        ["AT"] = new("AT(cSearchExpression, cExpressionSearched [, nOccurrence])", "N", "Position of the nth occurrence (0 if not found). Case-sensitive."),
        ["ATC"] = new("ATC(cSearchExpression, cExpressionSearched [, nOccurrence])", "N", "Like AT(), case-insensitive."),
        ["BETWEEN"] = new("BETWEEN(eTestValue, eLowValue, eHighValue)", "L", "True if the value is within the range (inclusive)."),
        ["BITAND"] = new("BITAND(nExpression1, nExpression2 [, …])", "N", "Bitwise AND."),
        ["BOF"] = new("BOF([nWorkArea | cTableAlias])", "L", "True if the record pointer is before the first record."),
        ["CDOW"] = new("CDOW(dExpression | tExpression)", "C", "Day of the week as a name."),
        ["CEILING"] = new("CEILING(nExpression)", "N", "Smallest integer ≥ the value."),
        ["CHR"] = new("CHR(nCharacterCode)", "C", "Character for a character code."),
        ["CHRTRAN"] = new("CHRTRAN(cSearchedExpression, cSearchExpression, cReplacementExpression)", "C", "Translates characters one-for-one."),
        ["CMONTH"] = new("CMONTH(dExpression | tExpression)", "C", "Month name."),
        ["CREATEOBJECT"] = new("CREATEOBJECT(cClassName [, eParameter1, …])", "O", "Creates an object from a class; Init receives the parameters."),
        ["CTOD"] = new("CTOD(cCharacterExpression)", "D", "Converts text in the SET DATE format to a date."),
        ["CTOT"] = new("CTOT(cCharacterExpression)", "T", "Converts text to a datetime."),
        ["CURSORGETPROP"] = new("CURSORGETPROP(cProperty [, nWorkArea | cTableAlias])", "V", "Reads a cursor property (Buffering, SourceType…)."),
        ["CURSORSETPROP"] = new("CURSORSETPROP(cProperty [, eExpression] [, nWorkArea | cTableAlias])", "L", "Sets a cursor property, e.g. CURSORSETPROP(\"Buffering\", 5)."),
        ["CURVAL"] = new("CURVAL(cExpression [, nWorkArea | cTableAlias])", "V", "Value currently stored on disk (buffering)."),
        ["DATE"] = new("DATE([nYear, nMonth, nDay])", "D", "Today's date, or a date from its parts."),
        ["DATETIME"] = new("DATETIME([nYear, nMonth, nDay [, nHours [, nMinutes [, nSeconds]]]])", "T", "Current datetime, or one from its parts."),
        ["DAY"] = new("DAY(dExpression | tExpression)", "N", "Day of the month."),
        ["DBF"] = new("DBF([cTableAlias | nWorkArea])", "C", "Full name of the table open in a work area."),
        ["DELETED"] = new("DELETED([cTableAlias | nWorkArea])", "L", "True if the current record is marked for deletion."),
        ["DODEFAULT"] = new("DODEFAULT([eParameter1, …])", "V", "Runs the parent class's version of the current method."),
        ["DOW"] = new("DOW(dExpression | tExpression [, nFirstDayOfWeek])", "N", "Day of the week as a number (1 = Sunday by default)."),
        ["DTOC"] = new("DTOC(dExpression | tExpression [, 1])", "C", "Date as text in the SET DATE format (YYYYMMDD with 1)."),
        ["DTOS"] = new("DTOS(dExpression | tExpression)", "C", "Date as YYYYMMDD (for index keys)."),
        ["EMPTY"] = new("EMPTY(eExpression)", "L", "True for blank strings, 0, empty dates and .F.; .NULL. is not empty."),
        ["EOF"] = new("EOF([nWorkArea | cTableAlias])", "L", "True if the record pointer is past the last record."),
        ["EVALUATE"] = new("EVALUATE(cExpression)", "V", "Evaluates an expression stored in a string."),
        ["EVL"] = new("EVL(eExpression1, eExpression2)", "V", "eExpression1 unless it is empty or .NULL., else eExpression2."),
        ["EXECSCRIPT"] = new("EXECSCRIPT(cExpression [, eParameter1, …])", "V", "Runs FoxPro code stored in a string."),
        ["FCOUNT"] = new("FCOUNT([nWorkArea | cTableAlias])", "N", "Number of fields in the table."),
        ["FIELD"] = new("FIELD(nFieldNumber [, nWorkArea | cTableAlias])", "C", "Name of a field by position."),
        ["FILE"] = new("FILE(cFileName)", "L", "True if the file exists."),
        ["FILETOSTR"] = new("FILETOSTR(cFileName)", "C", "Returns the contents of a file."),
        ["FLOOR"] = new("FLOOR(nExpression)", "N", "Largest integer ≤ the value."),
        ["FOUND"] = new("FOUND([nWorkArea | cTableAlias])", "L", "True if the last SEEK, LOCATE or CONTINUE succeeded."),
        ["GETFLDSTATE"] = new("GETFLDSTATE(cFieldName | nFieldNumber [, cTableAlias | nWorkArea])", "N", "1 unchanged, 2 changed, 3/4 appended (buffering)."),
        ["GETWORDCOUNT"] = new("GETWORDCOUNT(cString [, cDelimiters])", "N", "Number of words."),
        ["GETWORDNUM"] = new("GETWORDNUM(cString, nIndex [, cDelimiters])", "C", "The nth word."),
        ["GOMONTH"] = new("GOMONTH(dExpression | tExpression, nNumberOfMonths)", "D", "Date n months before or after."),
        ["ICASE"] = new("ICASE(lCondition1, eResult1 [, lCondition2, eResult2 …] [, eOtherwiseResult])", "V", "Inline DO CASE."),
        ["IIF"] = new("IIF(lExpression, eExpression1, eExpression2)", "V", "Inline IF: only the chosen branch is evaluated."),
        ["INLIST"] = new("INLIST(eExpression1, eExpression2 [, eExpression3 …])", "L", "True if the first value equals any of the others."),
        ["INT"] = new("INT(nExpression)", "N", "Integer part (truncates toward zero)."),
        ["ISNULL"] = new("ISNULL(eExpression)", "L", "True if the value is .NULL."),
        ["LEFT"] = new("LEFT(cExpression, nExpression)", "C", "Leftmost characters."),
        ["LEN"] = new("LEN(cExpression)", "N", "Number of characters."),
        ["LIKE"] = new("LIKE(cPattern, cExpression)", "L", "Wildcard match (* and ?)."),
        ["LOWER"] = new("LOWER(cExpression)", "C", "Converts to lowercase."),
        ["LTRIM"] = new("LTRIM(cExpression [, nFlags] [, cParseChar …])", "C", "Removes leading blanks."),
        ["MAX"] = new("MAX(eExpression1, eExpression2 [, …])", "V", "Largest value."),
        ["MESSAGEBOX"] = new("MESSAGEBOX(eMessageText [, nDialogBoxType [, cTitleBarText [, nTimeout]]])", "N", "Shows a message box; returns the button pressed."),
        ["MIN"] = new("MIN(eExpression1, eExpression2 [, …])", "V", "Smallest value."),
        ["MOD"] = new("MOD(nDividend, nDivisor)", "N", "Remainder; takes the sign of the divisor."),
        ["MONTH"] = new("MONTH(dExpression | tExpression)", "N", "Month number."),
        ["NEWOBJECT"] = new("NEWOBJECT(cClassName [, cModule [, cInApplication [, eParameter1, …]]])", "O", "Creates an object from a class in a given program or library."),
        ["NVL"] = new("NVL(eExpression1, eExpression2)", "V", "eExpression2 if eExpression1 is .NULL."),
        ["OCCURS"] = new("OCCURS(cSearchExpression, cExpressionSearched)", "N", "Number of occurrences."),
        ["OLDVAL"] = new("OLDVAL(cExpression [, cTableAlias | nWorkArea])", "V", "Original value before buffered edits."),
        ["ORDER"] = new("ORDER([nWorkArea | cTableAlias [, nPath]])", "C", "Name of the controlling index tag."),
        ["PADC"] = new("PADC(eExpression, nResultSize [, cPadCharacter])", "C", "Centers and pads to a length."),
        ["PADL"] = new("PADL(eExpression, nResultSize [, cPadCharacter])", "C", "Pads on the left."),
        ["PADR"] = new("PADR(eExpression, nResultSize [, cPadCharacter])", "C", "Pads on the right."),
        ["PCOUNT"] = new("PCOUNT()", "N", "Number of parameters passed to the current procedure."),
        ["PEMSTATUS"] = new("PEMSTATUS(oObject | cClassName, cProperty | cEvent | cMethod | cObject, nAttribute)", "V", "Information about a property/event/method (5 = exists)."),
        ["PROGRAM"] = new("PROGRAM([nLevel])", "C", "Name of the executing program or procedure."),
        ["PROPER"] = new("PROPER(cExpression)", "C", "Capitalizes each word."),
        ["RAT"] = new("RAT(cSearchExpression, cExpressionSearched [, nOccurrence])", "N", "Position of the nth occurrence from the right."),
        ["RECCOUNT"] = new("RECCOUNT([nWorkArea | cTableAlias])", "N", "Number of records (including deleted ones)."),
        ["RECNO"] = new("RECNO([nWorkArea | cTableAlias])", "N", "Current record number."),
        ["REPLICATE"] = new("REPLICATE(cExpression, nTimes)", "C", "Repeats a string."),
        ["RIGHT"] = new("RIGHT(cExpression, nCharacters)", "C", "Rightmost characters."),
        ["RLOCK"] = new("RLOCK([nWorkArea | cTableAlias] | [cRecordNumberList, nWorkArea | cTableAlias])", "L", "Locks the current (or listed) records."),
        ["ROUND"] = new("ROUND(nExpression, nDecimalPlaces)", "N", "Rounds half away from zero."),
        ["RTRIM"] = new("RTRIM(cExpression [, nFlags] [, cParseChar …])", "C", "Removes trailing blanks."),
        ["SEEK"] = new("SEEK(eExpression [, nWorkArea | cTableAlias [, nIndexNumber | cTagName]])", "L", "Searches an index; moves the record pointer."),
        ["SELECT"] = new("SELECT([0 | 1 | cTableAlias])", "N", "Current work area number, or the number of an alias."),
        ["SET"] = new("SET(cSETCommand [, 1 | cExpression | 2 | 3])", "V", "Current value of a SET command, e.g. SET(\"EXACT\")."),
        ["SPACE"] = new("SPACE(nSpaces)", "C", "A string of blanks."),
        ["SQRT"] = new("SQRT(nExpression)", "N", "Square root."),
        ["STR"] = new("STR(nExpression [, nLength [, nDecimalPlaces]])", "C", "Number as text (default length 10, no decimals)."),
        ["STREXTRACT"] = new("STREXTRACT(cSearchExpression, cBeginDelim [, cEndDelim [, nOccurrence [, nFlag]]])", "C", "Text between delimiters."),
        ["STRTOFILE"] = new("STRTOFILE(cExpression, cFileName [, lAdditive | nFlag])", "N", "Writes a string to a file; returns bytes written."),
        ["STRTRAN"] = new("STRTRAN(cSearched, cExpressionSought [, cReplacement [, nStartOccurrence [, nNumberOfOccurrences [, nFlags]]]])", "C", "Replaces occurrences of a string."),
        ["STUFF"] = new("STUFF(cExpression, nStartReplacement, nCharactersReplaced, cReplacement)", "C", "Replaces part of a string."),
        ["SUBSTR"] = new("SUBSTR(cExpression, nStartPosition [, nCharactersReturned])", "C", "Part of a string."),
        ["SYS"] = new("SYS(nFunction [, …])", "V", "System information (SYS(2015) unique name, SYS(5) drive, SYS(2003) folder…)."),
        ["TABLEREVERT"] = new("TABLEREVERT([lAllRows [, cTableAlias | nWorkArea]])", "N", "Discards buffered changes; returns the number of records reverted."),
        ["TABLEUPDATE"] = new("TABLEUPDATE([nRows [, lForce [, cTableAlias | nWorkArea [, cErrorArray]]]])", "L", "Commits buffered changes; .F. on an update conflict."),
        ["TEXTMERGE"] = new("TEXTMERGE(cExpression [, lRecursive [, cLeftDelim [, cRightDelim]]])", "C", "Replaces <<expressions>> in text."),
        ["TIME"] = new("TIME([nExpression])", "C", "Current time as HH:MM:SS."),
        ["TRANSFORM"] = new("TRANSFORM(eExpression [, cFormatCodes])", "C", "Formats a value as text (picture masks, @ functions)."),
        ["TRIM"] = new("TRIM(cExpression [, nFlags] [, cParseChar …])", "C", "Removes trailing blanks."),
        ["TTOC"] = new("TTOC(tExpression [, 1 | 2 | 3])", "C", "Datetime as text (1 = YYYYMMDDHHMMSS, 3 = XML format)."),
        ["TTOD"] = new("TTOD(tExpression)", "D", "Date part of a datetime."),
        ["TYPE"] = new("TYPE(cExpression [, 1])", "C", "Type of an expression given as a string ('U' if undefined)."),
        ["UPPER"] = new("UPPER(cExpression)", "C", "Converts to uppercase."),
        ["USED"] = new("USED([nWorkArea | cTableAlias])", "L", "True if a table is open in the work area."),
        ["VAL"] = new("VAL(cExpression)", "N", "Numeric value of text."),
        ["VARTYPE"] = new("VARTYPE(eExpression [, lNullDataType])", "C", "Type letter of a value ('U' if undefined, 'X' for .NULL.)."),
        ["VERSION"] = new("VERSION([nExpression])", "V", "Version information."),
        ["YEAR"] = new("YEAR(dExpression | tExpression)", "N", "Year."),
    });

    public static readonly IReadOnlyDictionary<string, string> Commands = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["USE"] = "USE [TableName | ?] [IN nWorkArea | cTableAlias] [AGAIN] [ALIAS cTableAlias] [ORDER [TAG] TagName] [EXCLUSIVE | SHARED] [NOUPDATE]",
        ["SELECT"] = "SELECT nWorkArea | cTableAlias — or SELECT-SQL: SELECT … FROM … [WHERE] [GROUP BY] [HAVING] [ORDER BY] [INTO CURSOR | ARRAY | TABLE]",
        ["REPLACE"] = "REPLACE FieldName1 WITH eExpression1 [ADDITIVE] [, …] [Scope] [FOR lExpression] [WHILE lExpression] [IN nWorkArea | cTableAlias]",
        ["SCAN"] = "SCAN [Scope] [FOR lExpression] [WHILE lExpression] … ENDSCAN",
        ["LOCATE"] = "LOCATE [Scope] FOR lExpression [WHILE lExpression]",
        ["SEEK"] = "SEEK eExpression [ORDER [TAG] TagName] [IN nWorkArea | cTableAlias]",
        ["INDEX"] = "INDEX ON eExpression TAG TagName [FOR lExpression] [ASCENDING | DESCENDING] [UNIQUE | CANDIDATE]",
        ["CREATE"] = "CREATE TABLE | CURSOR Name (Field Type [(nWidth [, nDecimals])] [NULL | NOT NULL] [CHECK …] [DEFAULT …] [PRIMARY KEY | UNIQUE] [AUTOINC], …)",
        ["APPEND"] = "APPEND BLANK [IN nWorkArea | cTableAlias] — APPEND FROM FileName [FOR lExpression] [FIELDS …] [TYPE …]",
        ["DELETE"] = "DELETE [Scope] [FOR lExpression] [WHILE lExpression] — or DELETE FROM Table [WHERE …]",
        ["SET"] = "SET EXACT | DELETED | ORDER TO | FILTER TO | RELATION TO | DEFAULT TO | DATE TO | CENTURY | DECIMALS TO | …",
        ["DO"] = "DO ProgramName | ProcedureName [IN ProgramName] [WITH ParameterList] — DO FORM FormName [NAME VarName] [WITH …] [TO VarName]",
        ["DEFINE"] = "DEFINE CLASS ClassName AS ParentClass [OF ClassLibrary] … ENDDEFINE",
        ["SCATTER"] = "SCATTER [FIELDS FieldList] [MEMO] [BLANK] MEMVAR | NAME ObjectName [ADDITIVE] | TO ArrayName",
        ["GATHER"] = "GATHER FROM ArrayName | MEMVAR | NAME ObjectName [FIELDS FieldList] [MEMO]",
        ["BROWSE"] = "BROWSE [FIELDS FieldList] [FOR lExpression] — opens an editable grid",
        ["IMPORT"] = "IMPORT FOXPRO cFileOrFolder [TO cTargetFolder] — converts FoxPro tables, databases or a whole folder",
        ["SORT"] = "SORT TO TableName ON FieldName1 [/A | /D] [/C] [, …] [ASCENDING | DESCENDING] [Scope] [FOR lExpression] [WHILE lExpression] [FIELDS FieldList]",
        ["TOTAL"] = "TOTAL TO TableName ON FieldName [FIELDS FieldList] [Scope] [FOR lExpression] [WHILE lExpression]",
        ["JOIN"] = "JOIN WITH nWorkArea | cTableAlias TO TableName FOR lExpression [FIELDS FieldList]",
        ["SAVE"] = "SAVE TO FileName | MEMO MemoFieldName [ALL LIKE Skeleton | ALL EXCEPT Skeleton]",
        ["RESTORE"] = "RESTORE FROM FileName | MEMO MemoFieldName [ADDITIVE]",
        ["ACCEPT"] = "ACCEPT [cPromptText] TO VarName",
        ["INPUT"] = "INPUT [cPromptText] TO VarName — the typed text is evaluated as an expression",
        ["KEYBOARD"] = "KEYBOARD cKeyboardValue [PLAIN] [CLEAR] — puts keys in the buffer INKEY() reads",
        ["ON"] = "ON ERROR [Command] | ON KEY LABEL KeyLabel [Command] | ON SHUTDOWN [Command] | ON ESCAPE [Command]",
        ["RUN"] = "RUN [/N] OperatingSystemCommand",
        ["DIR"] = "DIR [[ON Drive] [[LIKE] FileSkeleton]] [TO FILE FileName]",
        ["TYPE"] = "TYPE FileName [NUMBER] [TO FILE FileName]",
        ["LIST"] = "LIST [FieldList] [Scope] [FOR lExpression] [OFF] — LIST MEMORY | STATUS | OBJECTS | DATABASE | TABLES | VIEWS | FILES [TO FILE FileName]",
        ["DISPLAY"] = "DISPLAY [FieldList] [Scope] [FOR lExpression] — DISPLAY MEMORY | STATUS | STRUCTURE | …",
        ["DROP"] = "DROP TABLE TableName | DROP VIEW ViewName | DROP CONNECTION ConnectionName",
        ["EXPORT"] = "EXPORT TO FileName [TYPE] XLS [FIELDS FieldList] [Scope] [FOR lExpression]",
    };

    public static readonly string[] Keywords =
    [
        "ADD OBJECT", "ALTER TABLE", "APPEND", "APPEND BLANK", "BEGIN TRANSACTION", "BROWSE", "CASE", "CATCH", "CLEAR", "CLOSE DATABASES",
        "CLOSE TABLES", "CONTINUE", "COPY TO", "COUNT", "CREATE CURSOR", "CREATE DATABASE", "CREATE TABLE", "DEFINE CLASS", "DELETE",
        "DIMENSION", "DISPLAY", "DO", "DO CASE", "DO FORM", "DO WHILE", "ELSE", "END TRANSACTION", "ENDCASE", "ENDDEFINE", "ENDDO",
        "ENDFOR", "ENDFUNC", "ENDIF", "ENDPROC", "ENDSCAN", "ENDTEXT", "ENDTRY", "ENDWITH", "EXIT", "FINALLY", "FOR", "FOR EACH", "FUNCTION",
        "GATHER", "GO BOTTOM", "GO TOP", "IF", "IMPORT FOXPRO", "INDEX ON", "INSERT INTO", "LIST", "LOCAL", "LOCATE FOR", "LOOP",
        "LPARAMETERS", "MODIFY COMMAND", "NODEFAULT", "OPEN DATABASE", "OTHERWISE", "PACK", "PARAMETERS", "PRIVATE", "PROCEDURE",
        "PROTECTED", "PUBLIC", "READ EVENTS", "RECALL", "RELEASE", "REPLACE", "RETURN", "ROLLBACK", "SCAN", "SCATTER", "SEEK", "SELECT",
        "SET DELETED ON", "SET EXACT ON", "SET FILTER TO", "SET ORDER TO", "SET RELATION TO", "SKIP", "STORE", "SUM", "TEXT", "THROW",
        "TRY", "UPDATE", "USE", "WAIT WINDOW", "WITH", "ZAP",
    ];
}
