using System.Text;
using JoePro.Runtime.Builtins;

namespace JoePro.Tooling;

/// <summary>The language reference page (docs/reference/language.md), generated from the function registry and its docs.</summary>
public static class LanguageReference
{
    private static string TypeName(string code) => code switch
    {
        "C" => "Character", "N" => "Numeric", "L" => "Logical", "D" => "Date", "T" => "DateTime", "O" => "Object", "Y" => "Currency",
        "Q" => "Varbinary", "V" => "Varies", _ => "",
    };

    public static string Markdown()
    {
        var sb = new StringBuilder();
        var names = Library.Names.Where(n => !n.StartsWith("__")).Select(n => n.ToUpperInvariant()).Distinct().Order(StringComparer.Ordinal).ToList();
        sb.Append("# Joe Pro language reference\n\n");
        sb.Append("Generated by `joepro docs --reference` from the runtime's function registry. The same descriptions appear in the editor's hover, completion and signature help. ");
        sb.Append("For what is and is not supported relative to Visual FoxPro 9, see the [coverage matrix](coverage.md).\n\n");
        sb.Append("- [Functions](#functions) (").Append(names.Count).Append(")\n- [Commands](#commands)\n\n");
        sb.Append("## Functions\n\n");
        foreach (var group in names.GroupBy(n => char.IsLetter(n[0]) ? n[0] : '#'))
        {
            sb.Append("### ").Append(group.Key).Append("\n\n| Function | Returns | Description |\n|---|---|---|\n");
            foreach (var n in group)
            {
                var doc = FunctionDocs.Functions.GetValueOrDefault(n);
                sb.Append("| `").Append(Escape(doc?.Signature ?? n + "()")).Append("` | ").Append(TypeName(doc?.Returns ?? ""))
                  .Append(" | ").Append(Escape(doc?.Summary ?? "")).Append(" |\n");
            }
            sb.Append('\n');
        }
        sb.Append("## Commands\n\n");
        sb.Append("Syntax for the most used commands; every VFP 9 command's status is in the [coverage matrix](coverage.md).\n\n| Command | Syntax |\n|---|---|\n");
        foreach (var (k, v) in FunctionDocs.Commands.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            sb.Append("| ").Append(k).Append(" | ").Append(Escape(v)).Append(" |\n");
        return sb.ToString();
    }

    private static string Escape(string s) => s.Replace("|", "\\|");
}
