<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JoePro.Core\JoePro.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Headers\*.h" LogicalName="JoePro.Language.Headers.%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
